export const LOTTO = {
  UPPER: 45,
  LOWER: 1,
  COUNT: 6,
  PRICE: 1_000,
};

export const ERROR_MESSAGE = {
  PREFIX: "[ERROR]",
};

export const RANK = {
  FIRST: {
    DISPLAY: "FIRST",
    MATCH_COUNT: 6,
    PRICE: 2_000_000_000,
  },
  SECOND: {
    DISPLAY: "SECOND",
    MATCH_COUNT: 5,
    PRICE: 30_000_000,
  },
  THIRD: { DISPLAY: "THIRD", MATCH_COUNT: 5, PRICE: 1_500_000 },
  FOURTH: { DISPLAY: "FOURTH", MATCH_COUNT: 4, PRICE: 50_000 },
  FIFTH: { DISPLAY: "FIFTH", MATCH_COUNT: 3, PRICE: 5_000 },
};
